/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  canonicalUrl?: string;
  noIndex?: boolean;
};

export type FaqSection = {
  _type: "faqSection";
  heading?: string;
  items?: Array<{
    question?: string;
    answer?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "faqItem";
    _key: string;
  }>;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & Table)
  | ({
      _key: string;
    } & FaqSection)
>;

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  featured?: boolean;
  body?: BlockContent;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: string;
  link?: string;
};

export type Table = {
  _type: "table";
  rows?: Array<
    {
      _key: string;
    } & TableRow
  >;
};

export type TableRow = {
  _type: "tableRow";
  cells?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | FaqSection
  | BlockContent
  | Category
  | Slug
  | AuthorReference
  | CategoryReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | Table
  | TableRow
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]  | order(coalesce(publishedAt, _createdAt) desc) {    _id,    title,    "slug": slug.current,    excerpt,    featured,    publishedAt,    mainImage {   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions },    "author": author->{ name, role, "slug": slug.current },    "categories": categories[]->{ _id, title, "slug": slug.current }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  featured: boolean | null;
  publishedAt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
  } | null;
  author: {
    name: string | null;
    role: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    _updatedAt,    mainImage {   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions },    body[] {      ...,      _type == "image" => {   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions }    },    "author": author->{      name,      role,      bio,      link,      "slug": slug.current,      image {   ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions }    },    "categories": categories[]->{ _id, title, "slug": slug.current },    "seo": {      "title": coalesce(seo.metaTitle, title),      "description": coalesce(seo.metaDescription, excerpt),      "ogImage": coalesce(seo.ogImage, mainImage),      "canonicalUrl": seo.canonicalUrl,      "noIndex": seo.noIndex == true    }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  _updatedAt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "faqSection";
        heading?: string;
        items?: Array<{
          question?: string;
          answer?: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href?: string;
              openInNewTab?: boolean;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }>;
          _type: "faqItem";
          _key: string;
        }>;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      }
    | {
        _key: string;
        _type: "table";
        rows?: Array<
          {
            _key: string;
          } & TableRow
        >;
      }
  > | null;
  author: {
    name: string | null;
    role: string | null;
    bio: string | null;
    link: string | null;
    slug: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    ogImage:
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        }
      | null;
    canonicalUrl: string | null;
    noIndex: boolean | false;
  };
} | null;

// Source: sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POSTS_SITEMAP_QUERY
// Query: *[_type == "post" && defined(slug.current) && seo.noIndex != true]{    "slug": slug.current,    _updatedAt  }
export type POSTS_SITEMAP_QUERY_RESULT = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && defined(slug.current)]\n  | order(coalesce(publishedAt, _createdAt) desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    featured,\n    publishedAt,\n    mainImage { \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n },\n    "author": author->{ name, role, "slug": slug.current },\n    "categories": categories[]->{ _id, title, "slug": slug.current }\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    _updatedAt,\n    mainImage { \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n },\n    body[] {\n      ...,\n      _type == "image" => { \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n }\n    },\n    "author": author->{\n      name,\n      role,\n      bio,\n      link,\n      "slug": slug.current,\n      image { \n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n }\n    },\n    "categories": categories[]->{ _id, title, "slug": slug.current },\n    "seo": {\n      "title": coalesce(seo.metaTitle, title),\n      "description": coalesce(seo.metaDescription, excerpt),\n      "ogImage": coalesce(seo.ogImage, mainImage),\n      "canonicalUrl": seo.canonicalUrl,\n      "noIndex": seo.noIndex == true\n    }\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current) && seo.noIndex != true]{\n    "slug": slug.current,\n    _updatedAt\n  }\n': POSTS_SITEMAP_QUERY_RESULT;
  }
}
